pub fn get_help_content() -> Vec<String> {
    vec![
        "".to_string(),
        "  ██████╗ ███████╗██╗   ██╗██╗    ██╗".to_string(),
        "  ██╔══██╗██╔════╝██║   ██║██║    ██║".to_string(),
        "  ██████╔╝█████╗  ██║   ██║██║ █╗ ██║".to_string(),
        "  ██╔══██╗██╔══╝  ╚██╗ ██╔╝██║███╗██║".to_string(),
        "  ██║  ██║███████╗ ╚████╔╝ ╚███╔███╔╝".to_string(),
        "  ╚═╝  ╚═╝╚══════╝  ╚═══╝   ╚══╝╚══╝ ".to_string(),
        "".to_string(),
        "  A vim-like TUI for managing notes and resources".to_string(),
        "".to_string(),
        "═══════════════════════════════════════════════════════════════".to_string(),
        "".to_string(),
        "COMMAND LINE OPTIONS".to_string(),
        "".to_string(),
        "  revw [file.json]            - Open in interactive mode".to_string(),
        "  revw --edit file.json       - Open in Edit mode".to_string(),
        "  revw --stdout file.json     - Output to stdout".to_string(),
        "  revw --output file file.json - Output to file".to_string(),
        "  revw --inside file.json     - Output only INSIDE section".to_string(),
        "  revw --outside file.json    - Output only OUTSIDE section".to_string(),
        "  revw --markdown file.json   - Output in Markdown format".to_string(),
        "  revw -i data.json file.json - Input from file".to_string(),
        "  echo '{...}' | revw -i - file.json - Input from stdin (pipe)".to_string(),
        "  revw -i data.json -a file.json - Append input".to_string(),
        "".to_string(),
        "═══════════════════════════════════════════════════════════════".to_string(),
        "".to_string(),
        "VIEW MODE CONTROLS".to_string(),
        "".to_string(),
        "Navigation:".to_string(),
        "  j/k or ↑/↓   - select card (or mouse wheel)".to_string(),
        "  h/l or f/b   - scroll card content".to_string(),
        "  gg           - select first card".to_string(),
        "  G            - select last card".to_string(),
        "  :gi          - jump to first INSIDE entry".to_string(),
        "  :go          - jump to first OUTSIDE entry".to_string(),
        "  /            - search forward".to_string(),
        "  n/N          - next/prev match (jumps to card)".to_string(),
        "  :noh         - clear search highlighting".to_string(),
        "".to_string(),
        "Editing:".to_string(),
        "  Enter        - open edit overlay for selected card".to_string(),
        "  :ai          - add new INSIDE entry (jumps to it)".to_string(),
        "  :ao          - add new OUTSIDE entry (jumps to it)".to_string(),
        "  :o           - order entries (by percentage then name) and auto-save".to_string(),
        "  :op          - order by percentage only and auto-save".to_string(),
        "  :on          - order by name only and auto-save".to_string(),
        "  :or          - order randomly and auto-save".to_string(),
        "".to_string(),
        "Copy/Paste:".to_string(),
        "  :c           - copy all rendered content (with OUTSIDE/INSIDE headers)".to_string(),
        "  :ci          - copy INSIDE section only".to_string(),
        "  :co          - copy OUTSIDE section only".to_string(),
        "  :cj          - copy all content (JSON format)".to_string(),
        "  :cm          - copy all content (Markdown format)".to_string(),
        "  :cu          - copy URL from selected card".to_string(),
        "  :v           - paste file path or JSON content".to_string(),
        "  :vu          - paste URL from clipboard to selected card".to_string(),
        "  :vi          - paste INSIDE from clipboard (overwrite)".to_string(),
        "  :vo          - paste OUTSIDE from clipboard (overwrite)".to_string(),
        "  :va          - paste both INSIDE and OUTSIDE from clipboard (append)".to_string(),
        "  :vai         - paste INSIDE from clipboard (append)".to_string(),
        "  :vao         - paste OUTSIDE from clipboard (append)".to_string(),
        "  :xi          - clear INSIDE section".to_string(),
        "  :xo          - clear OUTSIDE section".to_string(),
        "".to_string(),
        "Entry Operations:".to_string(),
        "  :dd          - delete selected entry".to_string(),
        "  :yy          - duplicate selected entry".to_string(),
        "".to_string(),
        "Visual Mode (multi-card selection):".to_string(),
        "  v            - enter Visual mode".to_string(),
        "  j/k          - extend selection".to_string(),
        "  :cc          - copy selected cards (rendered)".to_string(),
        "  :ccj         - copy selected cards (JSON)".to_string(),
        "  :ccm         - copy selected cards (Markdown)".to_string(),
        "  :cct         - copy selected cards (Toon)".to_string(),
        "  :dc          - delete selected cards".to_string(),
        "  Esc/Ctrl+[   - exit Visual mode".to_string(),
        "".to_string(),
        "Filter (View mode only):".to_string(),
        "  :f pattern   - filter entries by pattern".to_string(),
        "  :nof         - clear filter".to_string(),
        "".to_string(),
        "Settings:".to_string(),
        "  :set number / :set nu       - enable line numbers (Edit mode)".to_string(),
        "  :set nonumber / :set nonu   - disable line numbers".to_string(),
        "  :set relativenumber / :set rnu - enable relative line numbers (Edit mode)".to_string(),
        "  :set norelativenumber / :set nornu - disable relative line numbers".to_string(),
        "  :set card=N                 - set max visible cards (1-10, default: 5)".to_string(),
        "  :set border=rounded         - use rounded border style (default)".to_string(),
        "  :set border=plain           - use plain border style".to_string(),
        "  :set extension              - show file extensions in explorer and window title".to_string(),
        "  :set noextension            - hide file extensions in explorer and window title".to_string(),
        "".to_string(),
        "File Explorer Commands (when explorer has focus):".to_string(),
        "  j/k or ↑/↓   - navigate files/directories".to_string(),
        "  h/l or ←/→   - scroll left/right (for long filenames)".to_string(),
        "  gg           - jump to first entry".to_string(),
        "  G            - jump to last entry".to_string(),
        "  /            - search files by name".to_string(),
        "  n/N          - next/prev search match".to_string(),
        "  Enter or o   - open file or expand/collapse directory".to_string(),
        "  ..           - navigate to parent directory".to_string(),
        "  :a           - create new JSON file".to_string(),
        "  :d           - create new directory".to_string(),
        "  :m           - rename file".to_string(),
        "  :dd          - delete file (confirms with yes/no)".to_string(),
        "  :yy          - copy file (asks destination)".to_string(),
        "".to_string(),
        "Other:".to_string(),
        "  r            - toggle View/Edit mode".to_string(),
        "  :Lexplore / :Lex / :lx - toggle file explorer (left)".to_string(),
        "  :outline / :ol - toggle card outline panel (right)".to_string(),
        "  Ctrl+w w     - cycle between windows".to_string(),
        "  Ctrl+w h     - move to explorer (left)".to_string(),
        "  Ctrl+w l     - move to outline (right)".to_string(),
        "  Ctrl+w j/k   - move to file (center)".to_string(),
        "  :h or ?      - help".to_string(),
        "  q or Esc     - quit".to_string(),
        "".to_string(),
        "EDIT MODE CONTROLS".to_string(),
        "".to_string(),
        "Navigation:".to_string(),
        "  h/j/k/l or arrow keys - move cursor".to_string(),
        "  e            - next word end".to_string(),
        "  b            - previous word start".to_string(),
        "  gg           - jump to top".to_string(),
        "  G            - jump to bottom".to_string(),
        "  :gi          - jump to first INSIDE entry".to_string(),
        "  :go          - jump to first OUTSIDE entry".to_string(),
        "".to_string(),
        "Editing:".to_string(),
        "  i            - enter insert mode".to_string(),
        "  x            - delete character at cursor".to_string(),
        "  X            - delete character before cursor".to_string(),
        "  dd           - delete current line".to_string(),
        "  yy           - yank (copy) current line".to_string(),
        "  p            - paste yanked line after current line".to_string(),
        "  Esc or Ctrl+[ - exit insert mode".to_string(),
        "  u            - undo".to_string(),
        "  Ctrl+r       - redo".to_string(),
        "  g-           - undo".to_string(),
        "  g+           - redo".to_string(),
        "".to_string(),
        "Search:".to_string(),
        "  /            - search forward".to_string(),
        "  n/N          - next/prev match".to_string(),
        "  :noh         - clear search highlighting".to_string(),
        "".to_string(),
        "Commands:".to_string(),
        "  :ai          - add INSIDE entry".to_string(),
        "  :ao          - add OUTSIDE entry".to_string(),
        "  :o           - order entries (by percentage then name)".to_string(),
        "  :op          - order by percentage only".to_string(),
        "  :on          - order by name only".to_string(),
        "  :or          - order randomly".to_string(),
        "  :dd          - delete current entry (entire object)".to_string(),
        "  :yy          - duplicate current entry (entire object)".to_string(),
        "  :ci          - copy INSIDE section (JSON format)".to_string(),
        "  :co          - copy OUTSIDE section (JSON format)".to_string(),
        "  :cj          - copy all content (JSON format)".to_string(),
        "  :cm          - copy all content (Markdown format)".to_string(),
        "  :ct          - copy all content (Toon format)".to_string(),
        "  :vi          - paste INSIDE from clipboard (overwrite)".to_string(),
        "  :vo          - paste OUTSIDE from clipboard (overwrite)".to_string(),
        "  :va          - paste both INSIDE and OUTSIDE from clipboard (append)".to_string(),
        "  :vai         - paste INSIDE from clipboard (append)".to_string(),
        "  :vao         - paste OUTSIDE from clipboard (append)".to_string(),
        "  :xi          - clear INSIDE section".to_string(),
        "  :xo          - clear OUTSIDE section".to_string(),
        "  :w           - save".to_string(),
        "  :wq          - save and quit".to_string(),
        "  :q           - quit".to_string(),
        "  :e           - reload file".to_string(),
        "  :ar          - toggle auto-reload (default: on)".to_string(),
        "  :markdown    - export to Markdown (same folder, .md extension)".to_string(),
        "  :pdf         - export to PDF (same folder, .pdf extension)".to_string(),
        "  :f pattern   - filter entries".to_string(),
        "  :nof         - clear filter".to_string(),
        "  :Lexplore / :Lex / :lx - toggle file explorer (left)".to_string(),
        "  :outline / :ol - toggle card outline panel (right)".to_string(),
        "  Ctrl+w w     - cycle between windows".to_string(),
        "  Ctrl+w h     - move to explorer (left)".to_string(),
        "  Ctrl+w l     - move to outline (right)".to_string(),
        "  Ctrl+w j/k   - move to file (center)".to_string(),
        "  :h or ?      - help".to_string(),
        "".to_string(),
        "Outline Panel (when focused):".to_string(),
        "  j/k          - navigate entries".to_string(),
        "  go           - preview entry (jump without closing)".to_string(),
        "  Enter        - jump to entry and release focus".to_string(),
        "  /            - search entries".to_string(),
        "  n/N          - next/prev search match".to_string(),
        "  gg/G         - jump to first/last entry".to_string(),
        "  q            - close outline".to_string(),
        "".to_string(),
        "Settings:".to_string(),
        "  :set number / :set nu       - enable line numbers".to_string(),
        "  :set nonumber / :set nonu   - disable line numbers".to_string(),
        "  :set relativenumber / :set rnu - enable relative line numbers".to_string(),
        "  :set norelativenumber / :set nornu - disable relative line numbers".to_string(),
        "  :set card=N                 - set max visible cards (1-10, default: 5)".to_string(),
        "  :set border=rounded         - use rounded border style (default)".to_string(),
        "  :set border=plain           - use plain border style".to_string(),
        "  :set extension              - show file extensions in explorer and window title".to_string(),
        "  :set noextension            - hide file extensions in explorer and window title".to_string(),
        "  :set json                   - set format to JSON (for unnamed files)".to_string(),
        "  :set markdown               - set format to Markdown (for unnamed files)".to_string(),
        "".to_string(),
        "Substitute:".to_string(),
        "  :s/foo/bar/     - substitute first occurrence in current line".to_string(),
        "  :s/foo/bar/g    - substitute all occurrences in current line".to_string(),
        "  :%s/foo/bar/    - substitute first occurrence in all lines".to_string(),
        "  :%s/foo/bar/g   - substitute all occurrences in all lines".to_string(),
    ]
}
